# Deny-All policy ==> very restrictive. Purpose is to gradually open up. Make sure
# to open up control plane traffic should you use solutions such as Dapr etc.
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-all
spec:
  #order: <priority> ==> you can use such priorities if you want to enforce it no matter what other policies do
  selector: projectcalico.org/namespace not in  {'default','kube-system', 'calico-system', 'tigera-operator','gatekeeper-system','kube-public','kube-node-lease'}
  types:
  - Ingress
  - Egress
  ingress:
  - action: Deny
  egress:
  - action: Deny
---
# Allow-DNS policy ==> must open this from scracth, else nothing works.
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-dns
spec:  
  selector: all()
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
  egress:
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: log-all-traffic
spec:  
  selector: all()
  types:
    - Ingress
    - Egress
  ingress:
    - action: Log
      source: {}
      destination: {}
  egress:
    - action: Log
      source: {}
      destination: {}
